export const clubDetails = [
  {
    club: "Man City",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "L", "N"],
  },
  {
    club: "Liverpool",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Brighton",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Arsenal",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Newcastle",
    matchesPlayed: 3,
    win: 2,
    draw: 1,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Brentford",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Aston Villa",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Bournemouth",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Nottm Forest",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Tottenham",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Chelsea",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Fulham",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "West Ham",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Man United",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Leicester City",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Crystal Palace",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Ipswich Town",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
  {
    club: "Wolves",
    matchesPlayed: 3,
    win: 3,
    draw: 0,
    lost: 0,
    goalsScored: 2,
    goalsAgainst: 2,
    goalDifference: 7,
    points: 9,
    lastFiveMatches: ["W", "W", "D", "N", "N"],
  },
];
